- file:
    state: directory
    path: /etc/systemd/system/docker.service.d/

- name: docker systemd override 
  template:
    src: docker/docker.conf
    dest: /etc/systemd/system/docker.service.d/docker.conf
  notify:
    - systemctl daemon-reload
    - docker restart 

- name: docker daemon.json template
  template:
    src: docker/daemon.json
    dest: /etc/docker/daemon.json
  notify:
    - systemctl daemon-reload
    - docker restart

# - name: flush handler 
#   meta: flush_handlers