vm_ip_address: 192.168.100.100
vm_memory: 4096
vm_cpu: 4

use_apache: false 
use_jenkins: false
use_kubernetes: true 
use_nexus: true

kube_ingress_proxy: traefik

overwrite_local_kubeconfig: true 

# Directories where to store the compiled kuernetes manifests
kube_deployment_dirs:
  - /app/kubernetes_deployments 
  - /app/kubernetes_deployments/master_deployments

master_deployments_dir: "/app/kubernetes_deployments/master_deployments"