kube_deployment_dirs:
  - /app/kubernetes_deployments 
  - /app/kubernetes_deployments/master_deployments

master_deployments_dir: "/app/kubernetes_deployments/master_deployments"

helm_version: 2.11.0