- name: restart docker
  service: 
    name: docker 
    state: restarted

- name: start docker 
  service:
    name: docker
    state: started 

- name: systemctl daemon reload
  shell: systemctl daemon-reload